# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import math
# GENERAL FORM

#beginning = 2
#previous = 0
# IN LOOP:
#(next_even) = beginning * 4 + previous
# //calcuate sum
#previous = beginning
#beginning = next_even


def even(n):
    beg = 2
    prev = 0
    soma = 0
    while beg < n:
        prox = 4*beg + prev
        soma += beg
        prev = beg
        beg = prox

    return soma


n = 4*(10**6)
print(even(n))
